server:
  port: 8282
  servlet:
    context-path: /test
easyapi:
  #全局默认配置
  #是否启用EasyApi框架
  #enable: true
  #是否开启自动生成swagger接口文档
  #enableSwagger: true
  #默认语言,请求中或者会话中不存在语言参数时的默认取值
  #locale: "zh_CN"
  #是否开启多语言翻译缓存
  #enableLanguageCache: false
  #多语言缓存的最长时间，单位秒
  #languageCacheSeconds: 180
  #防重复提交码过期时间
  #noSubmitRepeatTimeoutSeconds: 120
  #用户会话失效时间
  #sessionExpireSeconds: 600
  #当未找到该语言的翻译时，是否使用默认翻译内容
  #alwaysUseDefaultLocale: false
  #是否强制对所有api响应添加响应壳
  #forceAutoAddResponseWrapper: true
  #根包名集合,以逗号分隔
  basePackages: "com.pddon.framework.demo.easyapi"
  #是否在控制台打印所有配置信息
  #printAllProperties: true
  error: #错误码相关配置
    #自定义系统错误码值,格式【枚举名 ：数值】
    systemErrorCodes:
      NOT_FOUND: 404
    #业务异常定义，格式【错误码多语言字典值 ：错误码指代的默认中文翻译描述信息】
    #业务错误码默认起始值
    businessCodeStart: 200001
    #业务错误码默认最大值
    businessCodeEnd: 999999
    #业务异常错误码值
    businessErrorCodes:
      USER_ACCOUNT_NOT_FOUND.desc: "用户账号[{0}]未找到!"
      ACCOUNT_NOT_FOUND:
        code: 200006
        desc: "账户[{0}]未找到！"
  api:
    #业务接口api包名
    swagger:
      #业务接口所在根包名，swagger会扫描这个包下的内容，生成接口文档
      basePackage: "com.pddon.framework.demo.easyapi.controller"
      title: "业务API"
      description: "所有业务接口列表"
      termsOfServiceUrl: "www.pddon.cn"
      contact: "service@pddon.com"
      version: "v1.0.0"
    #api请求系统参数配置
    request:
      parameter:
        otherParams: #其他额外系统参数
          - "appName"
          - "nickName"
          - "tagId"
          #rename: #重命名系统参数
          #channelId: "buId"
          #api响应系统参数配置
          #response:
          #field:
          #rename: #重命名系统响应参数
          #code: "status"
    #渠道、应用信息配置
    channels:
      default: #用于不区分渠道信息的应用
        default: #默认的秘钥信息
          enable: true
          #用于对称加解密、生成数字签名、验证数字签名的秘钥
          secret: "123456"
          keyPair: #用于非对称加解密的秘钥对
            privateSecret: ""
            publicSecret: ""
        webApp: #某个应用下的秘钥信息
          enable: true
          #用于对称加解密、生成数字签名、验证数字签名的秘钥
          secret: "NKVNcuwwEF76622A"
          keyPair: #用于非对称加解密的秘钥对
            privateSecret: ""
            publicSecret: ""
      android:
        default:
          enable: true
          #用于对称加解密、生成数字签名、验证数字签名的秘钥
          secret: "123456"
          keyPair: #用于非对称加解密的秘钥对
            privateSecret: ""
            publicSecret: ""
      ios:
        default:
          enable: true
          secret: "12345678"
          keyPair:
            privateSecret: ""
            publicSecret: ""

logging:
  level:
    org.springframework.web: INFO
    com.pddon.framework.easyapi: TRACE